apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "linux-audit-exporter.fullname" . }}
  labels: {{ include "linux-audit-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "linux-audit-exporter.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "linux-audit-exporter.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{ include "linux-audit-exporter.podAnnotations" . | nindent 8 }}
        {{- end }}
    spec:
      hostPID: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
      - name: linux-audit-exporter
        image: {{ template "linux-audit-exporter.image" .}}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - name: http
          containerPort: 9090
        readinessProbe: {{ toYaml .Values.readinessProbe | nindent 10 }}
        livenessProbe: {{ toYaml .Values.livenessProbe | nindent 10 }}
        {{- if .Values.securityContext }}
        securityContext: {{ toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
