name: ci

on:
  push:
    branches: '**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.12'
      - uses: actions/checkout@v2
      - name: Build
        run: make build
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.12'
      - uses: actions/checkout@v2
      - name: Lint
        run: make lint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.12'
      - uses: actions/checkout@v2
      - name: Lint
        run: make test
